= Вступ до Perl6
Naoum Hankache <naoum@hankache.com>; Дмитро Ясколко <mescalito.ua@gmail.com>;
:description:  Загальна інтродукція до Perl 6
:keywords: perl6, perl 6, введення, perl6intro, введення до perl 6, інтродукція до 6, вивчення perl6
:Revision: 0.1
:icons: font
:source-highlighter: pygments
//:pygments-style: manni
:source-language: perl6
:pygments-linenums-mode: table
:toc: left
:toc-title: Зміст
:doctype: book
:lang: uk

Цей документ має на меті надати швидкий огляд мови програмування Perl 6.
Новачкам у Perl 6 цей документ надасть можливість почати вивчення та виркористання цієї мови.

Деякі розділи цього документа посилаються на інші (більш досконалі та точні) частини http://docs.perl6.org[документації до Perl 6]. 
Вам слід прочитати їх, якщо потребуєте більше інформації на окремі теми.

Всюди у цьому документі ви знайдете приклади до найбільш обговорюваних тем. Аби краще їх зрозуміти, будь ласка, знайдіть трохи часу аби відтворити їх.

.Ліцензія
Цей документ ліцензовано за міжнародною ліцензією Creative Commons Attribution Share-Alike 4.0 (Із зазначенням авторства — Розповсюдження на тих самих умовах)
Аби побачити копію цієї лізензії, перейдіть за посиланням:

* https://creativecommons.org/licenses/by-sa/4.0/.

.Долучення
Якщо ви хочете долучитися до вдосконалення цього документа, перейдіть до:

* https://github.com/hankache/perl6intro

.Відгуки
Будь-які відгуки вдячно ся приймають на:

* naoum@hankache.com - English
* mescalito.ua@gmail.com - Українська

Якщо вам сподобалася ця робота, позначте зірочкою репозиторій за посиланням: link:https://github.com/hankache/perl6intro[Github].

.Переклади
* Болгарська: http://bg.perl6intro.com
* Іспанська: http://es.perl6intro.com
* Китайська: http://zh.perl6intro.com
* Німецька: http://de.perl6intro.com
* Португальська: http://pt.perl6intro.com
* Фразцузька: http://fr.perl6intro.com
* Голандська: http://nl.perl6intro.com
* Японська: http://ja.perl6intro.com
* Українська: http://uk.perl6intro.com

:sectnums:

== Вступ
=== Що таке Perl 6
Perl 6 це високорівнева мова програмування загального призначення з поступовою типізацією.
Perl 6 є багатопарадигмальною мовою, яка підтримує Процедурне, Об'єктно-орієнтоване та Функціональне програмування.

.Гасло Perl 6: 
* ІБНОСЗЦ Існує більш ніж один спосіб зробити це. TMTOWTDI (Вимовляється Tim Toady).
* Прості речі мають лишатися простими, складні мають простішати, а неможливі мають стати складними.

=== Визначення
* *Perl 6*: Позначення  мови програмування в межах добірки тестів.
Реалізації, які проходять добірку тестів без помилок, вважаються Perl 6.
* *Rakudo*: Компілятор Perl 6.
* *Rakudobrew*: менеджер встановлення Rakudo.
* *Zef*: встановлювач модулів Perl 6.
* *Rakudo Star*: колекція, яка містить Rakudo, Zef, добірку модулів Perl 6 та документацію.

=== Встановлення Perl 6.
.Linux

Аби встановити Rakudo Star, виконайте наступні команди в своєму терміналі:
----
wget https://rakudo.perl6.org/downloads/star/rakudo-star-2017.07.tar.gz
tar xfz rakudo-star-2017.07.tar.gz
cd rakudo-star-2017.07
perl Configure.pl --gen-moar --prefix /opt/rakudo-star-2017.07
make install
----
Аби дізнатися по інші способи, перейдіть до http://rakudo.org/how-to-get-rakudo/#Installing-Rakudo-Star-Linux

.macOS
Доступними є чотири варіанти:
* Дотримуватися тих самих кроків, що й для Linux
* Встановити через homebrew: `brew install rakudo-star`
* Встановити з MacPorts: `sudo port install rakudo` 
* Завантажити останній встановлювач з https://rakudo.perl6.org/downloads/star/ (файл з розширенням .dmg)

.Windows
. Завантажте останній встановлювач (файл з розширенням .msi) з https://rakudo.perl6.org/downloads/star/ +
Якщо у вас 32-бітна система, завантажте файл х86; якщо 64-бітна, файл х86_64.
. Піcля встановлення переконайтеся,  що `C:\rakudo\bin` додано до змінної PATH.

.Docker
. Отримайте офіційний образ для Docker `docker pull rakudo-star`
. Далі запустіть контейнер з цим образом `docker run -it rakudo-star`

=== Виконання коду Perl 6


