= Вступ до Perl6
Naoum Hankache <naoum@hankache.com>; Дмитро Ясколко <mescalito.ua@gmail.com>;
:description:  Загальна інтродукція до Perl 6
:keywords: perl6, perl 6, введення, perl6intro, введення до perl 6, інтродукція до 6, вивчення perl6
:Revision: 0.1
:icons: font
:source-highlighter: pygments
//:pygments-style: manni
:source-language: perl6
:pygments-linenums-mode: table
:toc: left
:toc-title: Зміст
:doctype: book
:lang: uk

Цей документ має на меті надати швидкий огляд мови програмування Perl 6.
Новачкам у Perl 6 цей документ надасть можливість почати вивчення та виркористання цієї мови.

Деякі розділи цього документа посилаються на інші (більш досконалі та точні) частини http://docs.perl6.org[документації до Perl 6]. 
Вам слід прочитати їх, якщо потребуєте більше інформації на окремі теми.

Всюди у цьому документі ви знайдете приклади до найбільш обговорюваних тем. Аби краще їх зрозуміти, будь ласка, знайдіть трохи часу аби відтворити їх.

.Ліцензія
Цей документ ліцензовано за міжнародною ліцензією Creative Commons Attribution Share-Alike 4.0 (Із зазначенням авторства — Розповсюдження на тих самих умовах).
Аби побачити копію цієї лізензії, перейдіть за посиланням:

* https://creativecommons.org/licenses/by-sa/4.0/.

.Долучення
Якщо ви хочете долучитися до вдосконалення цього документа, перейдіть до:

* https://github.com/hankache/perl6intro

.Відгуки
Будь-які відгуки вдячно ся приймають на:

* naoum@hankache.com - English
* mescalito.ua@gmail.com - Українська

Якщо вам сподобалася ця робота, позначте зірочкою репозиторій за посиланням: link:https://github.com/hankache/perl6intro[Github].

.Переклади
* Англійська: http://perl6intro.com
* Болгарська: http://bg.perl6intro.com
* Іспанська: http://es.perl6intro.com
* Китайська: http://zh.perl6intro.com
* Німецька: http://de.perl6intro.com
* Португальська: http://pt.perl6intro.com
* Фразцузька: http://fr.perl6intro.com
* Голандська: http://nl.perl6intro.com
* Японська: http://ja.perl6intro.com
* Українська: http://uk.perl6intro.com

:sectnums:

== Вступ
=== Що таке Perl 6
Perl 6 це високорівнева мова програмування загального призначення з поступовою типізацією.
Perl 6 є багатопарадигмальною мовою, яка підтримує Процедурне, Об'єктно-орієнтоване та Функціональне програмування.

.Гасло Perl 6: 
* ІБНОСЗЦ Існує більш ніж один спосіб зробити це. TMTOWTDI (Вимовляється Tim Toady).
* Прості речі мають лишатися простими, складні мають простішати, а неможливі мають стати складними.

=== Визначення
* *Perl 6*: Позначення  мови програмування в межах добірки тестів.
Реалізації, які проходять добірку тестів без помилок, вважаються Perl 6.
* *Rakudo*: Компілятор Perl 6.
* *Rakudobrew*: менеджер встановлення Rakudo.
* *Zef*: встановлювач модулів Perl 6.
* *Rakudo Star*: колекція, яка містить Rakudo, Zef, добірку модулів Perl 6 та документацію.

=== Встановлення Perl 6.
.Linux

Аби встановити Rakudo Star, виконайте наступні команди в своєму терміналі:
----
wget https://rakudo.perl6.org/downloads/star/rakudo-star-2017.07.tar.gz
tar xfz rakudo-star-2017.07.tar.gz
cd rakudo-star-2017.07
perl Configure.pl --gen-moar --prefix /opt/rakudo-star-2017.07
make install
----
Аби дізнатися по інші способи, перейдіть до http://rakudo.org/how-to-get-rakudo/#Installing-Rakudo-Star-Linux

.macOS
Доступними є чотири варіанти:

* Дотримуватися тих самих кроків, що й для Linux
* Встановити через homebrew: `brew install rakudo-star`
* Встановити з MacPorts: `sudo port install rakudo` 
* Завантажити останній встановлювач з https://rakudo.perl6.org/downloads/star/ (файл з розширенням .dmg)

.Windows
. Завантажте останній встановлювач (файл з розширенням .msi) з https://rakudo.perl6.org/downloads/star/ +
Якщо у вас 32-бітна система, завантажте файл х86; якщо 64-бітна, файл х86_64.
. Піcля встановлення переконайтеся,  що `C:\rakudo\bin` додано до змінної PATH.

.Docker
. Отримайте офіційний образ для Docker `docker pull rakudo-star`
. Далі запустіть контейнер з цим образом `docker run -it rakudo-star`

=== Виконання коду Perl 6

Виконувати код Perl 6 можна в режимі інтерактивного інтерпретатора команд або REPL (Read-Eval-Print Loop). Для цього відкрийте вікно терміналу, наберіть `perl6` та натисніть [Enter]. Це призведе до появи запрошення `>`. Далі, наберіть рядок коду та натисніть [Enter], інтрерпретатор надрукує значення або результат виконання цього рядка. Далі ви можете ввести інший рядок, або набрати `exit` та натиснути [Enter] аби завершити сесію інтерпретатора.

Також ви можете записати свій код у файл, зберегти та виконати його. Є рекомендованим надавати скриптам Perl 6 розширення `.pl6`. Виконати такий файл можна набравши `perl6 ваш_скрипт.pl6` у термінальному вікні та натиснувши [Enter]. На відміну від інтерактивного режиму це не призведе до негайного друку результатів виконання коду: код має містити команди на кшталт `say` аби надрукувати результати виконання.

Інтерактивний режим здебільшого вживають, коли треба виконати якийсь конкретний фрагмент коду, зазвичай єдиний рядок. Програми більші за один рядое краще зберігати у файл і потім виконувати їх. 

Один рядок можна також виконати з командного рядка в неінтерактивному режимі,  написавши `perl6 -e 'ваш код тут'` та натиснувши [Enter].       	 

[Підказка]
--
Rakudo Star вже містить редактор, який  допоможе вам отримати якнайбільше від інтерактивного режиму.

Якщо ви встановили звичайний Rakudo замість Rakudo Star, тоді ви, можливо, не маєте змоги редагувати рядки (стрілки вгору та вниз для навігації по історії, ліворуч та праворуч для редарування поточного рядку, TAB для автодоповненя). Виконайте наступні команди, аби отримати все це:

* `zef install Linenoise` спрацює на Windows, Linux та MacOS
* `zef install Readline` якщо у вас Linux та ви полюбляєте бібліотеку _Readline_
--

=== Текстові редактори

Оскільки більшість часу ми писатимемо та зберігатимемо  наші програми Perl 6 у файлах, нам стане у пригоді пристойний текстовий редактор, який розуміє синтаксис Perl 6. 

Особисто я надаю перевагу http://www.vim.org/[Vim], автор оригінального (англомовного) тексту використовує https://atom.io/[Atom] - це модерні текстові редактори, які вміють  підсвічувати синтаксис Perl 6 одразу після встановлення. https://atom.io/packages/language-perl6[Perl 6 FE] це альтернативний плагін для підсвічування синтаксису, який походить від оригінального пакету, але містить багато виправлень та доповнень. 
	
Інші люди у спільноті користуються https://www.gnu.org/software/emacs/[Emacs] чи http://padre.perlide.org/[Padre].

Свіжі версії Vim розуміють синтаксис Perl 6 одразу після встановлення, Emacs та Padre  потребуюьт встановлення додаткових пакетів.


=== Вітаю Світ!

Ми почнемо з ритуалу `Вітаю світ`.

[source,perl6]
say 'Вітання Світові!';

Це також може бути написане як

[source,perl6]
'Вітаю світ!'.say;

===  Огляд синтаксису

Perl 6 є *вільним за формою*: більшість часу ви можете використовувати довільну кількість пробілів, проте у певних випадках  пробіл  має значення.

*Твердження* це, зазвичай, логічний рядок коду, який має закінчуватися крапкою з комою:
`say "Hello" if True;`

*Вираз* це спеціальний тип твердження, який повертає значення:
`1+2` поверне `3`

*Значення* бувають:

* *Змінними*: це значення, якіими можно керувати за міняти.
* *Літералами*: це сталі значення, як число чи рядок.

*Оператори* класифіковані за типами:

|===

| *Тип* | *Пояснення* | *Приклад*

| Префіксні | Перед значенням | ++1

| Інфіксні | Між значеннями | 1+2

| Постфіксні | Після значення | 1++

| Контейнерні | Навколо значення | (1)

| Постконтейнерні | Після значення, навколо іншого | Array[1]

|===

==== Ідентифікатори

Ідентифікатори, це імена, які ви даєте значенням, коли визначаете їх.

.Правила:
* Вони мають починатися з алфавітного символа, чи нижнього  підкреслювання
* Вони можуть містити числа, за винятком першого символа
* Вони можуть містити дефіси та апострофи (за винятком першої та останньої позиції) за умови, що праворуч від кожного дефіса чи апострофа знаходиться алфавітний символ.

|===

| Вірно | Невірно

| var1 | 1var

| var-one | var-1

| var'one | var'1

| var1_ | var1'

| _var1 | -var

| змінна1 | 1змінна

|=== 

.Угода іменування

* Стиль верблюда: `variableNo1`

* Шашличний стиль: `variable-no1`

* Стиль змії: `variable_no1`

Ви можете довільно іменувати ваші ідентифікатори, але ознакою гарного тону є використання якогось одного стилю.

Використання осмислених назв полегшить ваше життя (та життя інших).

* `var1 = var2 * var3` синтаксично вірно, але призначення кожної змінної не є очевидним.
* `monthly-salary = daily-rate * working-days` значно кращій варіант іменування змінних. 
 
==== Коментарі
Коментар, це текст, ігнорований компілятором, який слугує для пояснення (саме пояснення, а не цитування) коду.

Коментарі ся поділяють на три типи:

* Однорядкові:
+
[source,perl6]
# Це коментар в один рядок

* Вбудовані:
+
[source,perl6]
say #`(Це вбудований коментар) "Hello World."

* Багаторядкові:
+
[source,perl6]
-----------------------------
=begin comment
Це багаторядковий коментар.
Коментар 1
Коментар 2
=end comment
-----------------------------

==== Лапки

Рядки мають бути обмежені поодинокими, чи подвійними лапками.

Завжди використовуйте подвійні лапки якщо:

* Ваш рядок містить апостроф

* Ваш рядок містить  змінну, яку має бути розгорнуто.

[source,perl6]
-----------------------------------
say 'Вітаю, Світ';   # Вітаю, Світ 
say "Вітаю, світ";   # Вітаю, Світ
say "Об'єм";         # Об'єм
my $name = 'Андрій Кузьменко';
say 'Вітаю $name';   # Вітаю $name
say "Вітаю $name";   # Вітаю Андрій Кузьменко
-----------------------------------

== Оператори

#TODO
